/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as miscRouteRouteImport } from './routes/(misc)/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as miscSettingIndexRouteImport } from './routes/(misc)/setting/index'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainCChatIdRouteImport } from './routes/(main)/c/$chatId'
import { Route as ApiAiMessageIndexRouteImport } from './routes/api/ai/message/index'
import { Route as ApiAiChatIndexRouteImport } from './routes/api/ai/chat/index'
import { Route as ApiV1AiMessageIndexRouteImport } from './routes/api/v1/ai/message/index'

const miscRouteRoute = miscRouteRouteImport.update({
  id: '/(misc)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const miscSettingIndexRoute = miscSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => miscRouteRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainCChatIdRoute = mainCChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiAiMessageIndexRoute = ApiAiMessageIndexRouteImport.update({
  id: '/api/ai/message/',
  path: '/api/ai/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatIndexRoute = ApiAiChatIndexRouteImport.update({
  id: '/api/ai/chat/',
  path: '/api/ai/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AiMessageIndexRoute = ApiV1AiMessageIndexRouteImport.update({
  id: '/api/v1/ai/message/',
  path: '/api/v1/ai/message/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/setting/': typeof miscSettingIndexRoute
  '/api/ai/chat/': typeof ApiAiChatIndexRoute
  '/api/ai/message/': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message/': typeof ApiV1AiMessageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/setting': typeof miscSettingIndexRoute
  '/api/ai/chat': typeof ApiAiChatIndexRoute
  '/api/ai/message': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message': typeof ApiV1AiMessageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(misc)': typeof miscRouteRouteWithChildren
  '/(main)/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(misc)/setting/': typeof miscSettingIndexRoute
  '/api/ai/chat/': typeof ApiAiChatIndexRoute
  '/api/ai/message/': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message/': typeof ApiV1AiMessageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/$chatId'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/dashboard/'
    | '/setting/'
    | '/api/ai/chat/'
    | '/api/ai/message/'
    | '/api/v1/ai/message/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$chatId'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/setting'
    | '/api/ai/chat'
    | '/api/ai/message'
    | '/api/v1/ai/message'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/(misc)'
    | '/(main)/c/$chatId'
    | '/api/auth/$'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(main)/dashboard/'
    | '/(misc)/setting/'
    | '/api/ai/chat/'
    | '/api/ai/message/'
    | '/api/v1/ai/message/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  miscRouteRoute: typeof miscRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAiChatIndexRoute: typeof ApiAiChatIndexRoute
  ApiAiMessageIndexRoute: typeof ApiAiMessageIndexRoute
  ApiV1AiMessageIndexRoute: typeof ApiV1AiMessageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(misc)': {
      id: '/(misc)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof miscRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(misc)/setting/': {
      id: '/(misc)/setting/'
      path: '/setting'
      fullPath: '/setting/'
      preLoaderRoute: typeof miscSettingIndexRouteImport
      parentRoute: typeof miscRouteRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/c/$chatId': {
      id: '/(main)/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof mainCChatIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/ai/message/': {
      id: '/api/ai/message/'
      path: '/api/ai/message'
      fullPath: '/api/ai/message/'
      preLoaderRoute: typeof ApiAiMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat/': {
      id: '/api/ai/chat/'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat/'
      preLoaderRoute: typeof ApiAiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ai/message/': {
      id: '/api/v1/ai/message/'
      path: '/api/v1/ai/message'
      fullPath: '/api/v1/ai/message/'
      preLoaderRoute: typeof ApiV1AiMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainCChatIdRoute: typeof mainCChatIdRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainCChatIdRoute: mainCChatIdRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface miscRouteRouteChildren {
  miscSettingIndexRoute: typeof miscSettingIndexRoute
}

const miscRouteRouteChildren: miscRouteRouteChildren = {
  miscSettingIndexRoute: miscSettingIndexRoute,
}

const miscRouteRouteWithChildren = miscRouteRoute._addFileChildren(
  miscRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  miscRouteRoute: miscRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAiChatIndexRoute: ApiAiChatIndexRoute,
  ApiAiMessageIndexRoute: ApiAiMessageIndexRoute,
  ApiV1AiMessageIndexRoute: ApiV1AiMessageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
