/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as miscRouteRouteImport } from './routes/(misc)/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as miscSettingRouteImport } from './routes/(misc)/setting'
import { Route as mainDashboardRouteImport } from './routes/(main)/dashboard'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainCChatIdRouteImport } from './routes/(main)/c.$chatId'
import { Route as ApiAiMessageIndexRouteImport } from './routes/api/ai/message/index'
import { Route as ApiV1AiMessageIndexRouteImport } from './routes/api/v1/ai/message/index'

const miscRouteRoute = miscRouteRouteImport.update({
  id: '/(misc)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const miscSettingRoute = miscSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => miscRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainCChatIdRoute = mainCChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiAiMessageIndexRoute = ApiAiMessageIndexRouteImport.update({
  id: '/api/ai/message/',
  path: '/api/ai/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AiMessageIndexRoute = ApiV1AiMessageIndexRouteImport.update({
  id: '/api/v1/ai/message/',
  path: '/api/v1/ai/message/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof mainDashboardRoute
  '/setting': typeof miscSettingRoute
  '/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/message/': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message/': typeof ApiV1AiMessageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof mainDashboardRoute
  '/setting': typeof miscSettingRoute
  '/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/message': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message': typeof ApiV1AiMessageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(misc)': typeof miscRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(misc)/setting': typeof miscSettingRoute
  '/(main)/c/$chatId': typeof mainCChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/message/': typeof ApiAiMessageIndexRoute
  '/api/v1/ai/message/': typeof ApiV1AiMessageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/setting'
    | '/c/$chatId'
    | '/api/auth/$'
    | '/api/ai/message/'
    | '/api/v1/ai/message/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/setting'
    | '/c/$chatId'
    | '/api/auth/$'
    | '/api/ai/message'
    | '/api/v1/ai/message'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/(misc)'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(main)/dashboard'
    | '/(misc)/setting'
    | '/(main)/c/$chatId'
    | '/api/auth/$'
    | '/api/ai/message/'
    | '/api/v1/ai/message/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  miscRouteRoute: typeof miscRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAiMessageIndexRoute: typeof ApiAiMessageIndexRoute
  ApiV1AiMessageIndexRoute: typeof ApiV1AiMessageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(misc)': {
      id: '/(misc)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof miscRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(misc)/setting': {
      id: '/(misc)/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof miscSettingRouteImport
      parentRoute: typeof miscRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/c/$chatId': {
      id: '/(main)/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof mainCChatIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/ai/message/': {
      id: '/api/ai/message/'
      path: '/api/ai/message'
      fullPath: '/api/ai/message/'
      preLoaderRoute: typeof ApiAiMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ai/message/': {
      id: '/api/v1/ai/message/'
      path: '/api/v1/ai/message'
      fullPath: '/api/v1/ai/message/'
      preLoaderRoute: typeof ApiV1AiMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainDashboardRoute: typeof mainDashboardRoute
  mainCChatIdRoute: typeof mainCChatIdRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainDashboardRoute: mainDashboardRoute,
  mainCChatIdRoute: mainCChatIdRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface miscRouteRouteChildren {
  miscSettingRoute: typeof miscSettingRoute
}

const miscRouteRouteChildren: miscRouteRouteChildren = {
  miscSettingRoute: miscSettingRoute,
}

const miscRouteRouteWithChildren = miscRouteRoute._addFileChildren(
  miscRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  miscRouteRoute: miscRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAiMessageIndexRoute: ApiAiMessageIndexRoute,
  ApiV1AiMessageIndexRoute: ApiV1AiMessageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
